Environment:
	Python: 3.7.16
	PyTorch: 1.8.1
	Torchvision: 0.9.1
	CUDA: None
	CUDNN: None
	NumPy: 1.19.5
	PIL: 8.1.0
	Node: rohits-mbp.lan
Args:
	JTT_ERM_model_folder: None
	JTT_threshold: 0.5
	JTT_weight: 3.0
	adv_alpha: 0.1
	algorithm: ERM
	batch_size: 32
	checkpoint_freq: 200
	clf_head_ratio: 2.0
	concat_group: False
	data_type: normal
	dataset: MIMIC
	debug: False
	delete_model: False
	distmatch_penalty_weight: 0.1
	es_metric: worst_roc
	es_patience: 5
	exp_name: erm_baseline
	fairalm_eta: 0.001
	fairalm_surrogate: logistic
	fairalm_threshold: 0.5
	groupdro_eta: 0.1
	lr: 0.0001
	match_type: mean
	max_steps: 20000
	model: densenet
	num_classes: 2
	only_frontal: False
	output_dir: ./output/d19f67890b96917c8076232c5a184b12
	protected_attr: None
	seed: 0
	smaller_label_set: False
	subset_group: None
	task: Pneumothorax
	use_cache: False
	val_fold: 1
	val_subset: 12288
	weight_decay: 0.0
Number of parameters: 7479682
Traceback (most recent call last):
  File "/opt/miniconda3/envs/cxr_fairness/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/miniconda3/envs/cxr_fairness/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/rohitsonawane/Documents/CXR_Fairness/cxr_fairness/train.py", line 202, in <module>
    for xy in next(train_minibatches_iterator)]
  File "/Users/rohitsonawane/Documents/CXR_Fairness/cxr_fairness/lib/infinite_data_loader.py", line 86, in __iter__
    yield next(self._infinite_iterator)
  File "/opt/miniconda3/envs/cxr_fairness/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 517, in __next__
    data = self._next_data()
  File "/opt/miniconda3/envs/cxr_fairness/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1199, in _next_data
    return self._process_data(data)
  File "/opt/miniconda3/envs/cxr_fairness/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1225, in _process_data
    data.reraise()
  File "/opt/miniconda3/envs/cxr_fairness/lib/python3.7/site-packages/torch/_utils.py", line 429, in reraise
    raise self.exc_type(msg)
FileNotFoundError: Caught FileNotFoundError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/opt/miniconda3/envs/cxr_fairness/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 202, in _worker_loop
    data = fetcher.fetch(index)
  File "/opt/miniconda3/envs/cxr_fairness/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/opt/miniconda3/envs/cxr_fairness/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/Users/rohitsonawane/Documents/CXR_Fairness/cxr_fairness/data/data.py", line 87, in __getitem__
    x, y, meta = self.ds[idx]
  File "/Users/rohitsonawane/Documents/CXR_Fairness/cxr_fairness/data/data.py", line 128, in __getitem__
    img = np.array(Image.open(item["path"]))
  File "/opt/miniconda3/envs/cxr_fairness/lib/python3.7/site-packages/PIL/Image.py", line 2904, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: '/Users/rohitsonawane/Documents/MIMIC-CXR-JPG/files/p13/p13204499/s52148530/46b7a4a2-3d3d4f44-be236a0b-76eebb06-b7594e51.jpg'

